version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev

    image: express-demo-app-dev:latest

    ports:
      - "127.0.0.1:3015:3015"

    environment:
      NODE_ENV: development
      DEMO_EXPRESS_APP_PORT: 3015

    volumes:
      - ./data.db:/app/data.db
      - ./src:/app/src
